/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hs.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Avro schema for stock price */
@org.apache.avro.specific.AvroGenerated
public class StockPrice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 673451867141827176L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockPrice\",\"namespace\":\"com.hs.kafka.avro.model\",\"doc\":\"Avro schema for stock price\",\"fields\":[{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The identifier of the stock.\"},{\"name\":\"exchange\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The stock exchange the stock was traded.\"},{\"name\":\"tradeValue\",\"type\":\"double\",\"doc\":\"The value the stock was traded for.\"},{\"name\":\"currency\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The currency the stock was traded in.\"},{\"name\":\"tradeTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Epoch millis timestamp at which the stock trade took place.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<StockPrice> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockPrice> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockPrice> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockPrice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockPrice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockPrice to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockPrice from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockPrice instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockPrice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The identifier of the stock. */
  private java.lang.String symbol;
  /** The stock exchange the stock was traded. */
  private java.lang.String exchange;
  /** The value the stock was traded for. */
  private double tradeValue;
  /** The currency the stock was traded in. */
  private java.lang.String currency;
  /** Epoch millis timestamp at which the stock trade took place. */
  private java.time.Instant tradeTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockPrice() {}

  /**
   * All-args constructor.
   * @param symbol The identifier of the stock.
   * @param exchange The stock exchange the stock was traded.
   * @param tradeValue The value the stock was traded for.
   * @param currency The currency the stock was traded in.
   * @param tradeTime Epoch millis timestamp at which the stock trade took place.
   */
  public StockPrice(java.lang.String symbol, java.lang.String exchange, java.lang.Double tradeValue, java.lang.String currency, java.time.Instant tradeTime) {
    this.symbol = symbol;
    this.exchange = exchange;
    this.tradeValue = tradeValue;
    this.currency = currency;
    this.tradeTime = tradeTime.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return exchange;
    case 2: return tradeValue;
    case 3: return currency;
    case 4: return tradeTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = value$ != null ? value$.toString() : null; break;
    case 1: exchange = value$ != null ? value$.toString() : null; break;
    case 2: tradeValue = (java.lang.Double)value$; break;
    case 3: currency = value$ != null ? value$.toString() : null; break;
    case 4: tradeTime = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The identifier of the stock.
   */
  public java.lang.String getSymbol() {
    return symbol;
  }


  /**
   * Sets the value of the 'symbol' field.
   * The identifier of the stock.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'exchange' field.
   * @return The stock exchange the stock was traded.
   */
  public java.lang.String getExchange() {
    return exchange;
  }


  /**
   * Sets the value of the 'exchange' field.
   * The stock exchange the stock was traded.
   * @param value the value to set.
   */
  public void setExchange(java.lang.String value) {
    this.exchange = value;
  }

  /**
   * Gets the value of the 'tradeValue' field.
   * @return The value the stock was traded for.
   */
  public double getTradeValue() {
    return tradeValue;
  }


  /**
   * Sets the value of the 'tradeValue' field.
   * The value the stock was traded for.
   * @param value the value to set.
   */
  public void setTradeValue(double value) {
    this.tradeValue = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The currency the stock was traded in.
   */
  public java.lang.String getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * The currency the stock was traded in.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'tradeTime' field.
   * @return Epoch millis timestamp at which the stock trade took place.
   */
  public java.time.Instant getTradeTime() {
    return tradeTime;
  }


  /**
   * Sets the value of the 'tradeTime' field.
   * Epoch millis timestamp at which the stock trade took place.
   * @param value the value to set.
   */
  public void setTradeTime(java.time.Instant value) {
    this.tradeTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new StockPrice RecordBuilder.
   * @return A new StockPrice RecordBuilder
   */
  public static com.hs.kafka.avro.model.StockPrice.Builder newBuilder() {
    return new com.hs.kafka.avro.model.StockPrice.Builder();
  }

  /**
   * Creates a new StockPrice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockPrice RecordBuilder
   */
  public static com.hs.kafka.avro.model.StockPrice.Builder newBuilder(com.hs.kafka.avro.model.StockPrice.Builder other) {
    if (other == null) {
      return new com.hs.kafka.avro.model.StockPrice.Builder();
    } else {
      return new com.hs.kafka.avro.model.StockPrice.Builder(other);
    }
  }

  /**
   * Creates a new StockPrice RecordBuilder by copying an existing StockPrice instance.
   * @param other The existing instance to copy.
   * @return A new StockPrice RecordBuilder
   */
  public static com.hs.kafka.avro.model.StockPrice.Builder newBuilder(com.hs.kafka.avro.model.StockPrice other) {
    if (other == null) {
      return new com.hs.kafka.avro.model.StockPrice.Builder();
    } else {
      return new com.hs.kafka.avro.model.StockPrice.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockPrice instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockPrice>
    implements org.apache.avro.data.RecordBuilder<StockPrice> {

    /** The identifier of the stock. */
    private java.lang.String symbol;
    /** The stock exchange the stock was traded. */
    private java.lang.String exchange;
    /** The value the stock was traded for. */
    private double tradeValue;
    /** The currency the stock was traded in. */
    private java.lang.String currency;
    /** Epoch millis timestamp at which the stock trade took place. */
    private java.time.Instant tradeTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hs.kafka.avro.model.StockPrice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.exchange)) {
        this.exchange = data().deepCopy(fields()[1].schema(), other.exchange);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tradeValue)) {
        this.tradeValue = data().deepCopy(fields()[2].schema(), other.tradeValue);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.currency)) {
        this.currency = data().deepCopy(fields()[3].schema(), other.currency);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.tradeTime)) {
        this.tradeTime = data().deepCopy(fields()[4].schema(), other.tradeTime);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing StockPrice instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hs.kafka.avro.model.StockPrice other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exchange)) {
        this.exchange = data().deepCopy(fields()[1].schema(), other.exchange);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tradeValue)) {
        this.tradeValue = data().deepCopy(fields()[2].schema(), other.tradeValue);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.currency)) {
        this.currency = data().deepCopy(fields()[3].schema(), other.currency);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tradeTime)) {
        this.tradeTime = data().deepCopy(fields()[4].schema(), other.tradeTime);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * The identifier of the stock.
      * @return The value.
      */
    public java.lang.String getSymbol() {
      return symbol;
    }


    /**
      * Sets the value of the 'symbol' field.
      * The identifier of the stock.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder setSymbol(java.lang.String value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * The identifier of the stock.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * The identifier of the stock.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'exchange' field.
      * The stock exchange the stock was traded.
      * @return The value.
      */
    public java.lang.String getExchange() {
      return exchange;
    }


    /**
      * Sets the value of the 'exchange' field.
      * The stock exchange the stock was traded.
      * @param value The value of 'exchange'.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder setExchange(java.lang.String value) {
      validate(fields()[1], value);
      this.exchange = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'exchange' field has been set.
      * The stock exchange the stock was traded.
      * @return True if the 'exchange' field has been set, false otherwise.
      */
    public boolean hasExchange() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'exchange' field.
      * The stock exchange the stock was traded.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder clearExchange() {
      exchange = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradeValue' field.
      * The value the stock was traded for.
      * @return The value.
      */
    public double getTradeValue() {
      return tradeValue;
    }


    /**
      * Sets the value of the 'tradeValue' field.
      * The value the stock was traded for.
      * @param value The value of 'tradeValue'.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder setTradeValue(double value) {
      validate(fields()[2], value);
      this.tradeValue = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeValue' field has been set.
      * The value the stock was traded for.
      * @return True if the 'tradeValue' field has been set, false otherwise.
      */
    public boolean hasTradeValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tradeValue' field.
      * The value the stock was traded for.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder clearTradeValue() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * The currency the stock was traded in.
      * @return The value.
      */
    public java.lang.String getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * The currency the stock was traded in.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder setCurrency(java.lang.String value) {
      validate(fields()[3], value);
      this.currency = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * The currency the stock was traded in.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'currency' field.
      * The currency the stock was traded in.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradeTime' field.
      * Epoch millis timestamp at which the stock trade took place.
      * @return The value.
      */
    public java.time.Instant getTradeTime() {
      return tradeTime;
    }


    /**
      * Sets the value of the 'tradeTime' field.
      * Epoch millis timestamp at which the stock trade took place.
      * @param value The value of 'tradeTime'.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder setTradeTime(java.time.Instant value) {
      validate(fields()[4], value);
      this.tradeTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeTime' field has been set.
      * Epoch millis timestamp at which the stock trade took place.
      * @return True if the 'tradeTime' field has been set, false otherwise.
      */
    public boolean hasTradeTime() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'tradeTime' field.
      * Epoch millis timestamp at which the stock trade took place.
      * @return This builder.
      */
    public com.hs.kafka.avro.model.StockPrice.Builder clearTradeTime() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockPrice build() {
      try {
        StockPrice record = new StockPrice();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.String) defaultValue(fields()[0]);
        record.exchange = fieldSetFlags()[1] ? this.exchange : (java.lang.String) defaultValue(fields()[1]);
        record.tradeValue = fieldSetFlags()[2] ? this.tradeValue : (java.lang.Double) defaultValue(fields()[2]);
        record.currency = fieldSetFlags()[3] ? this.currency : (java.lang.String) defaultValue(fields()[3]);
        record.tradeTime = fieldSetFlags()[4] ? this.tradeTime : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockPrice>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockPrice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockPrice>
    READER$ = (org.apache.avro.io.DatumReader<StockPrice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










